name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run server
        run: npm start

      - name: Deploy to Supabase
        uses: "supabase/gotrue-action@v1"
        with:
          SUPABASE_URL: ${{ secrets.https://lkyshkrxezdxjwoxpdrx.supabase.co }}
          SUPABASE_ANON_KEY: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxreXNoa3J4ZXpkeGp3b3hwZHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQ5NzY1NjAsImV4cCI6MjAzMDU1MjU2MH0.HcmOuKDzAuaMGS3szhnORxLdLXZT3AV-9eDPi-8pCj4 }}
